version: '3.0'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    image: esmbot
    restart: unless-stopped
    volumes:
      - ./logs:/home/esmBot/.internal/logs
      - ./bot-help:/home/esmBot/help
      - ./bot-temp:/home/esmBot/temp
      - ./servers.json:/home/esmBot/.internal/servers.json
    env_file:
      - .env
    environment:
      OUTPUT: /home/esmBot/help/help.md
      TEMPDIR: /home/esmBot/temp

    networks:
      esmbot:
        ipv4_address: 172.20.0.2

volumes:
  bot-help:
  bot-temp:
  pg-data:

networks:
  esmbot:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24